name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  django:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Adjust to your project's Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install django requests yfinance bs4
          pip install -r requirements.txt || true  # Skip if no requirements.txt

      - name: Set up Django Database
        run: python manage.py migrate  # Set up the database schema

      - name: Run Django Tests
        run: python manage.py test  # Run your project's test cases
